version: "3.9"
services:
  elastic:
    image: elasticsearch:7.16.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  tt-scores:
    build: .
    ports:
      - "9000:5000"